services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: SCA
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: