services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16.3-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=spycat_api
      - POSTGRES_USER=spycat_api
      - POSTGRES_DB=spycat_api
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - data:$PGDATA

volumes:
  data: